# Generated by Django 4.2.5 on 2023-10-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.PositiveIntegerField(null=True)),
                ('dig_verificador', models.CharField(max_length=1, null=True)),
                ('id_usuario', models.PositiveIntegerField(blank=True, null=True)),
                ('id_planEstudio', models.PositiveIntegerField(blank=True, null=True)),
                ('id_semestreIngreso', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
