# Generated by Django 4.2.5 on 2023-11-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coordinadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinador',
            name='id_usuario',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
