# Generated by Django 4.2.5 on 2023-11-12 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_coordinadores', '0002_alter_coordinador_id_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Solicitud_Revision',
        ),
    ]
