# Generated by Django 4.2.5 on 2023-11-12 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_coordinadores', '0003_delete_solicitud_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinacion_docente',
            name='id_coordinacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_coordinadores.coordinacion_seccion'),
        ),
    ]
