# Generated by Django 4.2.5 on 2023-11-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud_Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('anterior_nota', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('actual_nota', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('fecha_creacion', models.DateField()),
                ('archivoAdjunto', models.FileField(blank=True, null=True, upload_to='')),
                ('respuesta', models.TextField(blank=True, default='', null=True)),
                ('fecha_respuesta', models.DateField(blank=True, default=0, null=True)),
                ('estado', models.CharField(choices=[('A', 'Aprobado'), ('R', 'Rechazado'), ('P', 'Pendiente'), ('E', 'En revisión')], default='', max_length=1)),
                ('id_estudiante', models.PositiveIntegerField()),
                ('id_docente', models.PositiveIntegerField()),
                ('id_evaluacion', models.PositiveIntegerField()),
                ('id_calificacion', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
