# Generated by Django 4.2.5 on 2023-10-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('semestre', models.IntegerField()),
                ('isActual', models.BooleanField(default=False)),
            ],
        ),
    ]
