# Generated by Django 4.2.5 on 2023-10-31 16:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('codigo', models.CharField(max_length=20)),
                ('nivel', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('componente', models.CharField(choices=[('L', 'Laboratorio'), ('T', 'Teoría')], max_length=1)),
                ('isMBI', models.BooleanField(default=False)),
                ('isAutogestionada', models.BooleanField(default=False)),
                ('id_coordinador', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('obs_privada', models.TextField(blank=True, default='')),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='observaciones/estudiantes/')),
                ('id_estudiante', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinacion_Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_docente', models.PositiveIntegerField()),
                ('id_coordinacion', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Coordinacion_Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinacion', models.CharField(max_length=1)),
                ('seccion', models.PositiveSmallIntegerField()),
                ('isActive', models.BooleanField(default=False)),
                ('bloques_horario', models.CharField(max_length=16)),
                ('id_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('fechaEvActual', models.DateField()),
                ('fechaEntrega', models.DateField(blank=True, null=True)),
                ('ponderacion', models.DecimalField(decimal_places=3, max_digits=4)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('E', 'Evaluada')], max_length=1)),
                ('obs_general', models.TextField(blank=True, default='')),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='observaciones/evaluacion/')),
                ('id_docente', models.PositiveIntegerField()),
                ('id_coordinacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_admin.coordinacion_seccion')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tipo_Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='semestre',
            name='semestre',
            field=models.IntegerField(choices=[(1, 1), (2, 2)]),
        ),
        migrations.CreateModel(
            name='Vicedecano_Docencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.PositiveIntegerField(null=True)),
                ('dig_verificador', models.CharField(max_length=1, null=True)),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subdirector_Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.PositiveIntegerField(null=True)),
                ('dig_verificador', models.CharField(max_length=1, null=True)),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud_Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('anterior_nota', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('actual_nota', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('fecha_creacion', models.DateField()),
                ('archivoAdjunto', models.FileField(blank=True, null=True, upload_to='')),
                ('respuesta', models.TextField(blank=True, default='', null=True)),
                ('fecha_respuesta', models.DateField(blank=True, default=0, null=True)),
                ('estado', models.CharField(choices=[('A', 'Aprobado'), ('R', 'Rechazado'), ('P', 'Pendiente'), ('E', 'En revisión')], default='', max_length=1)),
                ('id_estudiante', models.PositiveIntegerField()),
                ('id_docente', models.PositiveIntegerField()),
                ('id_calificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_admin.calificacion')),
                ('id_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.evaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='Plan_Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('year_creacion', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4)])),
                ('id_carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Jefe_Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.PositiveIntegerField(null=True)),
                ('dig_verificador', models.CharField(max_length=1, null=True)),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('siglas', models.CharField(blank=True, max_length=10)),
                ('id_vicedecano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.vicedecano_docencia')),
            ],
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='id_tipoEvaluacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_admin.tipo_evaluacion'),
        ),
        migrations.CreateModel(
            name='Estadistica_Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio_general', models.DecimalField(decimal_places=3, max_digits=4)),
                ('mejor_nota', models.DecimalField(decimal_places=3, max_digits=4)),
                ('peor_nota', models.DecimalField(decimal_places=3, max_digits=4)),
                ('desviacionEstandar', models.DecimalField(decimal_places=3, max_digits=4)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_coordinacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.coordinacion_seccion')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('id_facultad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_admin.facultad')),
                ('id_subdirector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.subdirector_docente')),
            ],
        ),
        migrations.AddField(
            model_name='coordinacion_seccion',
            name='id_semetre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.semestre'),
        ),
        migrations.CreateModel(
            name='Coordinacion_Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedioEstudiante', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('id_estudiante', models.PositiveIntegerField()),
                ('id_coordinacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.coordinacion_seccion')),
            ],
        ),
        migrations.AddField(
            model_name='carrera',
            name='id_departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.departamento'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='id_jefeCarrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.jefe_carrera'),
        ),
        migrations.CreateModel(
            name='Cambio_Ponderacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ponderacionAnterior', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ponderacionNueva', models.DecimalField(decimal_places=3, max_digits=4)),
                ('motivo', models.TextField()),
                ('fecha_cambio', models.DateField(null=True)),
                ('id_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.evaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='Cambio_nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anterior_nota', models.DecimalField(decimal_places=1, max_digits=2)),
                ('actual_nota', models.DecimalField(decimal_places=1, max_digits=2)),
                ('fecha_cambio', models.DateField(null=True)),
                ('motivo', models.TextField()),
                ('id_calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.calificacion')),
            ],
        ),
        migrations.CreateModel(
            name='Cambio_Fecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAnterior', models.DateField()),
                ('fechaNueva', models.DateField()),
                ('motivo', models.TextField()),
                ('fecha_cambio', models.DateField(null=True)),
                ('id_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.evaluacion')),
            ],
        ),
        migrations.AddField(
            model_name='calificacion',
            name='id_evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.evaluacion'),
        ),
        migrations.CreateModel(
            name='Asignaturas_PlanEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.asignatura')),
                ('id_planEstudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.plan_estudio')),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='id_tipoAsignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_admin.tipo_asignatura'),
        ),
    ]
