# Generated by Django 4.2.5 on 2023-11-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0004_alter_jefe_carrera_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdirector_docente',
            name='id_usuario',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vicedecano_docencia',
            name='id_usuario',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
